<?php
use Mpdf\Tag\Center;
$nomor = $_POST['nomor'];
$nama = $_POST['namaanak'];
$ttl = $_POST['ttl'];
$kebangsaan = $_POST['kebangsaan'];
$kelamin = $_POST['kelamin'];
$status = $_POST['status'];
$pekerjaan = $_POST['pekerjaan'];
$nik = $_POST['nik'];
$alamat = $_POST['alamat'];
$namaayah = $_POST['namaayah'];
$umurayah = $_POST['umurayah'];
$bangsaayah = $_POST['bangsaayah'];
$pekerjaanayah = $_POST['pekerjaanayah'];
$alamatayah = $_POST['alamatayah'];
$namaibu = $_POST['namaibu'];
$umuribu = $_POST['umuribu'];
$bangsaibu = $_POST['bangsaibu'];
$pekerjaanibu = $_POST['pekerjaanibu'];
$alamatibu = $_POST['alamatibu'];
$tanggalsurat = $_POST['tanggalsurat'];

require("../Web_Kelurahan_Kepuharjo/fpdf185/fpdf.php");
 
$pdf = new FPDF();
$pdf->AddPage();
$pdf->Image('../Web_Kelurahan_Kepuharjo/images/logohp.png',18,8,50);
$pdf->SetFont('Times','',14);
$pdf->SetXY(70,18);
$pdf->SetFontSize(14);
$pdf->Write(0,'PEMERINTAH KABUPATEN LUMAJANG');
$pdf->SetXY(85,24);
$pdf->SetFontSize(14);
$pdf->Write(0,'KECAMATAN LUMAJANG');
$pdf->SetFont('Times','',20);
$pdf->SetXY(75,30);
$pdf->SetFontSize(18);
$pdf->Write(0,'KELURAHAN KEPUHARJO');
$pdf->SetFont('TIMES','',14);
$pdf->SetXY(75,36);
$pdf->SetFontSize(14);
$pdf->Write(0,'Jl. Langsep No. 18 Telp. (0334) 888243');
$pdf->SetFont('TIMES','',14);
$pdf->SetXY(99,42);
$pdf->SetFontSize(14);
$pdf->Write(0,'LUMAJANG');

$pdf->SetXY(10,20);
$pdf->SetFont('Times','B',14);
$pdf->Cell(0,80,'SURAT KETERANGAN KENAL LAHIR',0,0,'C');
$pdf->SetFont('Times','');
$pdf->SetXY(70,62);
$pdf->SetFontSize(12);
$pdf->Write(10,'Nomor : ');
$pdf->Write(10,$nomor);
$pdf->SetFont('Times','');
$pdf->SetXY(40,80);
$pdf->SetFontSize(12);
$pdf->Write(0,'Yang bertanda tangan di bawah ini kami Lurah Kepuharjo Kecamatan ');
$pdf->SetFont('Times','');
$pdf->SetXY(25,86);
$pdf->SetFontSize(12);
$pdf->Write(0,'Lumajang Kabupaten Lumajang menerangkan bahwa : ');
$pdf->SetXY(25,96);
$pdf->SetFontSize(12);
$pdf->Write(0,'               Nama                               :');
$pdf->Write(0,$nama);
$pdf->SetXY(25,102);
$pdf->SetFontSize(12);
$pdf->Write(0,'               Tempat, Tanggal Lahir    :');
$pdf->Write(0,$ttl);
$pdf->SetXY(25,108);
$pdf->SetFontSize(12);
$pdf->Write(0,'               Jenis Kelamin                  :');
$pdf->Write(0,$kelamin);
$pdf->SetXY(25,114);
$pdf->SetFontSize(12);
$pdf->Write(0,'               Kebangsaan/Agama         :');
$pdf->Write(0,$kebangsaan);
$pdf->SetXY(25,120);    
$pdf->SetFontSize(12);
$pdf->Write(0,'               Status                               :');
$pdf->Write(0,$status);
$pdf->SetXY(25,126);
$pdf->SetFontSize(12);
$pdf->Write(0,'               Pekerjaan                         :');
$pdf->Write(0,$pekerjaan);
$pdf->SetXY(25,132);
$pdf->SetFontSize(12);
$pdf->Write(0,'               NIK                                  :');
$pdf->Write(0,$nik);
$pdf->SetXY(25,138);
$pdf->SetFontSize(12);
$pdf->Write(0,'               Alamat                             :');
$pdf->Write(0,$alamat);
$pdf->SetXY(40,150);
$pdf->SetFontSize(12);
$pdf->Write(0,'Adalah benar - benar anak dari :');
$pdf->SetXY(25,156);
$pdf->SetFontSize(12);
$pdf->Write(0,'                             Ayah                                                                        Ibu');
$pdf->SetXY(25,162);
$pdf->SetFontSize(12);
$pdf->Write(0,'     Nama                :                                                     Nama                :');
$pdf->SetXY(60,162);
$pdf->Write(0,$namaayah);
$pdf->SetXY(145,162);
$pdf->Write(0,$namaibu);
$pdf->SetXY(25,168);
$pdf->SetFontSize(12);
$pdf->Write(0,'     Umur                :                                                     Umur                :');
$pdf->SetXY(60,168);
$pdf->Write(0,$umurayah);
$pdf->SetXY(145,168);
$pdf->Write(0,$umuribu);
$pdf->SetXY(25,174);
$pdf->SetFontSize(12);
$pdf->Write(0,'     Bangsa/Agama :                                                     Bangsa/Agama :');
$pdf->SetXY(60,174);
$pdf->Write(0,$bangsaayah);
$pdf->SetXY(145,174);
$pdf->Write(0,$bangsaibu);
$pdf->SetXY(25,180);
$pdf->SetFontSize(12);
$pdf->Write(0,'     Pekerjaan          :                                                     Pekerjaan          :');
$pdf->SetXY(60,180);
$pdf->Write(0,$pekerjaanayah);
$pdf->SetXY(145,180);
$pdf->Write(0,$pekerjaanibu);
$pdf->SetXY(25,186);
$pdf->SetFontSize(12);
$pdf->Write(0,'     Alamat              :                                                     Alamat              :');
$pdf->SetXY(60,186);
$pdf->Write(0,$alamatayah);
$pdf->SetXY(145,186);
$pdf->Write(0,$alamatibu);
$pdf->SetXY(40,196);
$pdf->SetFontSize(12);
$pdf->Write(0,'Surat keterangan ini dipergunakan untuk persyaratan administrasi membuat Akta');
$pdf->SetXY(25,202);
$pdf->SetFontSize(12);
$pdf->Write(0,'Kelahiran.');
$pdf->SetXY(40,208);
$pdf->SetFontSize(12);
$pdf->Write(0,'Demikian surat keterangan ini kami buat untuk dapat dipergunakan sebagaimana ');
$pdf->SetXY(25,214);
$pdf->SetFontSize(12);
$pdf->Write(0,'mestinnya.');
$pdf->SetXY(45,220);
$pdf->SetFontSize(12);
$pdf->Write(0,'                                                                     Lumajang, ');
$pdf->Write(0,$tanggalsurat);
$pdf->SetXY(35,226);
$pdf->SetFontSize(14);
$pdf->Write(0,'                                                                   LURAH KEPUHARJO');
$pdf->SetXY(35,258);
$pdf->SetFontSize(14);
$pdf->Image('../Web_Kelurahan_Kepuharjo/images/ttd.png',120,235,50);
$pdf->Image('../Web_Kelurahan_Kepuharjo/images/stempel.png',110,230,40);
$pdf->SetXY(35,264);
$pdf->SetFontSize(14);
$pdf->Write(0,'                                                                MUHAMMAD SAIFUL,S.AP');
// $pdf->Write(100,$name);
// $pdf->Write(100,$email);
// $pdf->Write(100,$mobile);
//$pdf->Output('D', "filename.pdf", true);
$pdf->output();
?>