<?php
require("../Web_Kelurahan_Kepuharjo/fpdf185/fpdf.php");
 
$pdf = new FPDF();
$pdf->AddPage();
$pdf->Image('../Web_Kelurahan_Kepuharjo/images/logohp.png',18,8,50);
$pdf->SetFont('Times','',14);
$pdf->SetXY(70,18);
$pdf->SetFontSize(14);
$pdf->Write(0,'PEMERINTAH KABUPATEN LUMAJANG');
$pdf->SetXY(85,24);
$pdf->SetFontSize(14);
$pdf->Write(0,'KECAMATAN LUMAJANG');
$pdf->SetFont('Times','',20);
$pdf->SetXY(75,30);
$pdf->SetFontSize(18);
$pdf->Write(0,'KELURAHAN KEPUHARJO');
$pdf->SetFont('TIMES','',14);
$pdf->SetXY(75,36);
$pdf->SetFontSize(14);
$pdf->Write(0,'Jl. Langsep No. 18 Telp. (0334) 888243');
$pdf->SetFont('TIMES','',14);
$pdf->SetXY(99,42);
$pdf->SetFontSize(14);
$pdf->Write(0,'LUMAJANG');

    $pdf->SetXY(10,20);
    $pdf->SetFont('Times','B',14);
    $pdf->Cell(0,80,'SURAT KETERANGAN BELUM NIKAH',0,0,'C');
    $pdf->SetFont('Times','');
    $pdf->SetXY(70,62);
    $pdf->SetFontSize(12);
    $pdf->Write(10,'Nomor : ');
    //$pdf->Write(10,$nomor);
    $pdf->SetFont('Times','');
    $pdf->SetXY(40,80);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'Yang bertanda tangan di bawah ini kami Lurah Kepuharjo Kecamatan ');
    $pdf->SetFont('Times','');
    $pdf->SetXY(25,86);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'Lumajang Kabupaten Lumajang menerangkan bahwa : ');
    $pdf->SetXY(25,96);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'               Nama                               :');
    //$pdf->Write(0,$nama);
    $pdf->SetXY(25,102);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'               Tempat, Tanggal Lahir    :');
    //$pdf->Write(0,$ttl);
    $pdf->SetXY(25,108);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'               Jenis Kelamin                  :');
    //$pdf->Write(0,$kebangsaan);
    $pdf->SetXY(25,114);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'               Kebangsaan/Agama         :');
    //$pdf->Write(0,$status);
    $pdf->SetXY(25,120);    
    $pdf->SetFontSize(12);
    $pdf->Write(0,'               Status                               :');
    $pdf->SetXY(25,126);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'               Pekerjaan                         :');
    //$pdf->Write(0,$pekerjaan);
    $pdf->SetXY(25,132);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'               NIK                                  :');
    //$pdf->Write(0,$nik);
    $pdf->SetXY(25,138);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'               Alamat                             :');
    //$pdf->Write(0,$alamat);
    $pdf->SetXY(40,150);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'Adalah benar sampai dengan saat ini adalah warga kami dan menurut sepengetahuan ');
    $pdf->SetXY(25,156);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'kami. Bahwa nama yang tersebut di atas benar - benar belum pernah menikah. Surat Keterangan');
    $pdf->SetXY(25,162);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'ini dipergunakan untuk persyaratan _________ ');
    $pdf->SetXY(40,170);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'Demikian surat keterangan ini kami buat untuk dapat dipergunakan sebagaimana ');
    $pdf->SetXY(25,176);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'mestinnya.');
    $pdf->SetXY(45,200);
    $pdf->SetFontSize(12);
    $pdf->Write(0,'                                                                     Lumajang, ');
    //$pdf->Write(0,$tanggalsurat);
    $pdf->SetXY(45,200);
    $pdf->SetFont('Times','B',12);
    $pdf->Write(0,'Yang Bersangkutan');
    $pdf->SetXY(35,206);
    $pdf->SetFontSize(14);
    $pdf->Write(0,'                                                                    LURAH KEPUHARJO');
    $pdf->SetXY(35,206);
    $pdf->SetFontSize(14);
    $pdf->Image('../Web_Kelurahan_Kepuharjo/images/ttd.png',120,210,50);
    $pdf->Image('../Web_Kelurahan_Kepuharjo/images/stempel.png',110,200,40);
    $pdf->SetXY(35,240);
    $pdf->SetFontSize(14);
    $pdf->Write(0,'                                                                MUHAMMAD SAIFUL,S.AP');
    $pdf->SetXY(36,240);
    $pdf->SetFontSize(14);
    $pdf->Write(0,'(                                          )');
    // $pdf->Write(100,$name);
    // $pdf->Write(100,$email);
    // $pdf->Write(100,$mobile);
    //$pdf->Output('D', "filename.pdf", true);
$pdf->output();

?>